package com.rs.tool.youtube_sub.model;

public class VideoInfo {

    public Meta     meta;
    public Response response;

    public static class Response {
        public Captions captions;
    }

    public static class Captions {
        public String        video_url;
        public String        title;
        public int           available_captions_count;
        public CaptionInfo[] available_captions;
    }

    public static class CaptionInfo {
        public String  language;
        public String  caption_content_url;
        public boolean autogenerated;
        public boolean machinetranslated;
    }

}
